### ISSUE TITLE
select takes a lot of processing time even if not needed

### ISSUE THREAD

**Issue by PuKoren** [joshuah/sol-redis-pool#12]
When using sol-redis-pool and aquire/release, the select commands takes a lot a processing time.

Here is the New Relic insights on our live app:  

| Command | % Time | Avg calls | Avg time |
| --- | --- | --- | --- |
| Redis select | 35.1 | 2.65 | 28.9 |
| Redis get | 16.8 | 0.949 | 13.8 |
| http[gateway-http]	| 16.2 | 0.076 | 13.3 |
| Redis info | 0.5 | 0.412 | 0.416 |
| Redis auth | 0.5 | 0.412 | 0.381 |
| Redis setex | 0.2 | 0.11 | 0.175 |

As you can see there is 2 selects for every get (acquire, release), wasting 28ms while the get took 13

PR coming

**Comment by joshuah** [comment]
Merged and published to npm. Please be aware that if you issue a select after acquiring a client you must manually reset it before releasing it back to the pool.

**Comment by PuKoren** [comment]
Is there a way to get the currently selected DB over the redis driver?

We could handle that on https://github.com/joshuah/sol-redis-pool/blob/master/index.js#L117 to select it on aquire

**Comment by joshuah** [comment]
Looks like they added a way since the last time I looked. I will patch it tonight.

The `client.selected_db` value now changes when a user uses the `client.select(db)` command.

**Comment by joshuah** [comment]
Can you test out the branch https://github.com/joshuah/sol-redis-pool/tree/dbnumonrelease? This uses the built in selected_db value which is updated by the redis client. This also should prevent users from accidentally releasing a client back into the pool after they select a different database.

**Comment by PuKoren** [comment]
I think there is 1 potential issue with db 0 and falsey values, you can find my comment here
https://github.com/joshuah/sol-redis-pool/commit/f61b7435c8979c8321b8fdff8d0ab23c8fce0732#commitcomment-16319214
