### ISSUE TITLE
Issues with re-establishing connection with Redis after an outage

### ISSUE THREAD

**Issue by afrasso** [joshuah/sol-redis-pool#18]
I'm running into some issues testing how the pool will behave when there is a redis outage. We're using redis as a cache to our microservices, and when it goes down we want to bypass the cache, and when it comes back up we'd like to seamlessly start using the cache again.

The behavior I *think* I'm seeing is that when redis goes down, a connection is closed, but the pool keeps returning that same connection, and even after the redis server comes back up I get the same error, until finally after waiting ~30 seconds without trying to access the connection it is destroyed and a new one created (I think this is related to the (idleTimeoutMillis setting in the pool).

Full disclosure, I'm using this package indirectly via node-cache-manager-redis. The errors I'm getting are:
`AbortError: GET can't be processed. The connection is already closed.`
and
`AbortError: SETEX can't be processed. The connection is already closed.`

Any thoughts on what might be happening here?

Thanks.

**Comment by joshuah** [comment]
Fixed some reconnection issues in the 0.3.0 version.
