### ISSUE TITLE
the pool destory meet error.

### ISSUE THREAD

**Issue by murdercdh** [joshuah/sol-redis-pool#4]
when there is only one connect, and I release the pool. the timer scan will call destory later. and client already end. So the node process will be crash in line "client.end();"(no method defined)

 // The destroy function is called when client connection needs to be closed.
    poolSettings["destroy"] = function destroyClient(client) {
            client.end();
        self.emit("destroy", null);
    }

**Comment by joshuah** [comment]
Pushed to master branch.
