### ISSUE TITLE
Pool does not always pass port, host to createClient

### ISSUE THREAD

**Issue by randy-sesser-locm** [joshuah/sol-redis-pool#6]
We recently ran into an issue where if there is no Redis service running on localhost, we were getting `ECONNREFUSED` from the `node-redis` module. When I added a `throw new Error()` in the `createClient()` method, it pointed to `sol-redis-pool`. It appears that  `port` and `host` are not being passed to `redis.createClient()` even when passing in a different host and port in `redisSettings`. I'm not sure if this is a side effect of the `generic-pool` or something more specific to this `sol-redis-pool`. Sorry I can't be more specific at the moment. When I have time, I'll try to dig into the actual cause.

**Comment by joshuah** [comment]
I am unable to replicate this. Do you have any more information?

**Comment by randy-sesser-locm** [comment]
I don't, sorry. The only thing I can add is how to replicate.

1. Stop your local redis server
2. Configure an external redis server in redisSettings
3. Start the app

That's when this would cause problems. Also, I should mention, we are using node's [cluster](https://nodejs.org/api/cluster.html) module in our express app. Also, I believe this module was being used by [cache-manager-redis](https://github.com/dial-once/node-cache-manager-redis) which may also be the culprit. To be honest, we abandoned redis caching at the moment so I haven't had the time to really look into it. Feel free to close the issue. If we decide to revisit redis caching and we can't figure it out, I'll add to this at a later date.
