### ISSUE TITLE
Add db command

### ISSUE THREAD

**Issue by bf** [joshuah/sol-redis-pool#8]
It seems support for the db command is missing. Is there a reason for not including it or can I propose a pull request?

**Comment by joshuah** [comment]
Please test the dbselect branch.

https://github.com/joshuah/sol-redis-pool/tree/dbselect

**Comment by joshuah** [comment]
New version published to npm.

**Comment by bf** [comment]
This is brilliant, thank you very much. I can now finally switch back from our private repo to your official version :-)
